/**
 * Плагин для Webpack, генерирует файл routes.js с массивом роутов на основании информации из .vue файлов в каталоге views
 */
const { readFileSync, readdirSync, writeFileSync, existsSync } = require("fs");

/**
 * Сгенерировать текст скрипта с роутами
 * @param {array} options
 * @returns {string}
 */
const generateScript = (options) => {
  const capitalize = (s) =>
    s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
  return (
    `// This file was autogenerated by _generateModules script
` +
    options
      .map(
        (option) =>
          `import ${capitalize(option)} from "@/modules/${option}/store";`
      )
      .join("\n") +
    `

export default {
` +
    options.map((option) => `  ${capitalize(option)},`).join("\n") +
    `
};
`
  );
};

/**
 * Сгенерировать файл с роутами
 */
const generateModulesFile = () => {
  const options = [];
  readdirSync(__dirname + "/../modules").forEach((dir) => {
    if (existsSync(`${__dirname}/../modules/${dir}/store.ts`)) {
      options.push(dir);
    }
  });
  let newContent = generateScript(options);
  if ("" + readFileSync(`${__dirname}/modules.ts`) !== newContent) {
    writeFileSync(`${__dirname}/modules.ts`, newContent);
  }
};

module.exports = class GenerateModuelsPlugin {
  apply(compiler) {
    compiler.hooks.compile.tap(
      { name: "GenerateModules" },
      generateModulesFile
    );
  }
};
